INSERT INTO USER_ROLE (USER_ROLE_ID, USER_ROLE, ROLE_SHORT_DESCRIPTION) VALUES (1,'ADMIN', 'Admin User'); 
INSERT INTO USER_ROLE (USER_ROLE_ID, USER_ROLE, ROLE_SHORT_DESCRIPTION) VALUES (2,'USER', 'User'); 
INSERT INTO USER_ROLE (USER_ROLE_ID, USER_ROLE, ROLE_SHORT_DESCRIPTION) VALUES (3,'SCHOOLREP', 'School Representative'); 
INSERT INTO USER_ROLE (USER_ROLE_ID, USER_ROLE, ROLE_SHORT_DESCRIPTION) VALUES (4,'CUSTOMER', 'Customer');
INSERT INTO USER_ROLE (USER_ROLE_ID, USER_ROLE, ROLE_SHORT_DESCRIPTION) VALUES (5,'RENTER', 'Renter');
commit;